/**
 * Flat Spanish strings module. All user-facing text lives here so a future
 * i18n migration is a single-file refactor.
 */

export const STRINGS = {
  site: {
    name: "Fútbol Wiki",
    tagline: "La enciclopedia del fútbol en español",
    description:
      "Equipos, jugadores, ligas, partidos y torneos con fuentes verificadas.",
  },
  nav: {
    inicio: "Inicio",
    partidos: "Partidos",
    equipos: "Equipos",
    jugadores: "Jugadores",
    ligas: "Ligas",
    torneos: "Torneos",
    selecciones: "Selecciones",
    buscar: "Buscar",
    sobre: "Sobre el proyecto",
  },
  theme: {
    light: "Modo claro",
    dark: "Modo oscuro",
    system: "Sistema",
    toggle: "Cambiar tema",
  },
  empty: {
    partidos: {
      title: "Aún no hay partidos programados",
      body: "Cuando se actualicen los calendarios, los próximos encuentros aparecerán acá.",
      cta: "Explorar equipos",
    },
    equipos: {
      title: "Aún no hay equipos cargados",
      body: "Los equipos se publican a medida que se verifican sus fuentes.",
    },
    jugadores: {
      title: "Aún no hay jugadores cargados",
      body: "Los perfiles se publican a medida que se verifican sus fuentes.",
    },
    ligas: {
      title: "Aún no hay ligas cargadas",
      body: "Las ligas se publican a medida que se verifican sus fuentes.",
    },
    torneos: {
      title: "Aún no hay torneos cargados",
      body: "Los torneos se publican a medida que se verifican sus fuentes.",
    },
    selecciones: {
      title: "Aún no hay selecciones cargadas",
      body: "Las selecciones se publican a medida que se verifican sus fuentes.",
    },
    search: {
      title: "Sin resultados",
      body: "Intentá con otros términos o revisá la ortografía.",
    },
    historia: {
      title: "Aún sin historia detallada",
      body: "La historia detallada de este equipo se publicará próximamente.",
    },
    plantilla: {
      title: "Aún sin plantilla cargada",
      body: "La plantilla actual se publicará próximamente.",
    },
    matchContext: {
      title: "Sin contexto disponible aún",
      body: "El análisis previo se publicará antes del encuentro.",
    },
  },
  errors: {
    notFound: {
      title: "Página no encontrada",
      body: "La página que buscás no existe o fue movida.",
      cta: "Volver al inicio",
    },
    generic: {
      title: "Algo salió mal",
      body: "Ocurrió un error al cargar esta página. Probá de nuevo en unos segundos.",
      cta: "Reintentar",
    },
    forbidden: {
      title: "Sin permisos",
      body: "No tenés permisos para acceder a esta página.",
    },
  },
  comingSoon: {
    title: "Próximamente",
    body: "Esta sección se publicará cuando completemos su verificación con fuentes.",
  },
  match: {
    upcoming: "Próximamente",
    live: "En vivo",
    finished: "Finalizado",
    postponed: "Postergado",
    cancelled: "Cancelado",
    abandoned: "Suspendido",
    vs: "vs",
    h2h: "Historial entre ambos",
    keyFacts: "Datos destacados",
    narrative: "Análisis previo",
    lastMeeting: "Último enfrentamiento",
    events: "Eventos del partido",
    lineups: "Alineaciones",
    noEvents: "Aún no hay eventos registrados.",
    minute: "min",
    attendance: "Asistencia",
    stadium: "Estadio",
    round: "Jornada",
  },
  team: {
    founded: "Fundado en",
    dissolved: "Disuelto en",
    stadium: "Estadio",
    coach: "DT actual",
    nicknames: "Apodos",
    country: "País",
    history: "Historia",
    squad: "Plantilla actual",
    formerPlayers: "Ex-jugadores",
    seasons: "Temporadas",
    honors: "Títulos",
    primaryColor: "Colores",
    notFound: "Equipo no encontrado",
  },
  player: {
    fullName: "Nombre completo",
    knownAs: "Conocido como",
    birthDate: "Fecha de nacimiento",
    deathDate: "Fecha de fallecimiento",
    birthplace: "Lugar de nacimiento",
    position: "Posición",
    foot: "Pie hábil",
    height: "Estatura",
    weight: "Peso",
    currentTeam: "Club actual",
    shirtNumber: "Dorsal",
    career: "Trayectoria",
    nationalTeam: "Selección",
    honors: "Títulos",
    retired: "Retirado",
    biography: "Biografía",
    notFound: "Jugador no encontrado",
  },
  coach: {
    notFound: "Entrenador no encontrado",
    career: "Trayectoria",
    nationality: "Nacionalidad",
    currentTeam: "Equipo actual",
    biography: "Biografía",
  },
  league: {
    season: "Temporada",
    standings: "Tabla de posiciones",
    topScorers: "Goleadores",
    pastSeasons: "Temporadas anteriores",
    organizer: "Organiza",
    founded: "Fundada en",
    tier: {
      1: "Primera división",
      2: "Segunda división",
      3: "Tercera división",
    },
    notFound: "Liga no encontrada",
  },
  tournament: {
    editions: "Ediciones",
    champions: "Campeones históricos",
    records: "Récords",
    bracket: "Llaves",
    final: "Final",
    notFound: "Torneo no encontrado",
  },
  position: {
    GK: "Arquero",
    DEF: "Defensor",
    MID: "Mediocampista",
    FWD: "Delantero",
    UNKNOWN: "Por determinar",
  },
  foot: {
    LEFT: "Izquierdo",
    RIGHT: "Derecho",
    BOTH: "Ambos",
    UNKNOWN: "Sin información",
  },
  honor: {
    CHAMPION: "Campeón",
    RUNNER_UP: "Subcampeón",
    THIRD_PLACE: "Tercer lugar",
    TOP_SCORER: "Goleador",
    MVP: "MVP",
    GOLDEN_GLOVE: "Guante de Oro",
    GOLDEN_BOOT: "Bota de Oro",
    FAIR_PLAY: "Fair Play",
  },
  sourceType: {
    WIKIPEDIA_ES: "Wikipedia (es)",
    WIKIPEDIA_EN: "Wikipedia (en)",
    TRANSFERMARKT: "Transfermarkt",
    OFFICIAL_TEAM: "Sitio oficial del club",
    OFFICIAL_LEAGUE: "Sitio oficial de la liga",
    OFFICIAL_FEDERATION: "Federación",
    FBREF: "FBref",
    ESPN_DEPORTES: "ESPN Deportes",
    NEWS: "Medio de prensa",
    BOOK: "Libro",
    OTHER: "Otra fuente",
  },
  confederation: {
    CONMEBOL: "Conmebol",
    UEFA: "UEFA",
    AFC: "AFC",
    CAF: "CAF",
    CONCACAF: "Concacaf",
    OFC: "OFC",
  },
  search: {
    placeholder: "Buscar equipos, jugadores, ligas…",
    submit: "Buscar",
    resultsFor: (q: string) => `Resultados para "${q}"`,
    typeToSearch: "Escribí para buscar…",
  },
  source: {
    label: "Fuente",
    viewSource: "Ver fuente",
    accessedOn: "Consultada el",
    multipleSources: (n: number) => `${n} fuentes`,
  },
  citation: {
    sourcesLabel: "Fuentes",
  },
  about: {
    title: "Sobre el proyecto",
  },
  loading: "Cargando…",
  showMore: "Ver más",
  showLess: "Ver menos",
  back: "Volver",
  backToHome: "Volver al inicio",
  retry: "Reintentar",
} as const;
